[package]
name = "doki-test"
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
edition = "2018"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.14"
sycamore = {version = "*", features=["experimental-builder-html"]}
wasm-bindgen = "0.2.78"

[dependencies.doki-core]
version = "0.1"
path = "../doki-core"