[workspace]
members = ["projects/*"]
default-members = [
    "projects/doki-core",
    "projects/doki-git",
]
exclude = [
    "projects/.DS_Store",
    "projects/doki-docs",
]

[profile.release]
lto = true
panic = "abort"
