[[sections]]
title = "Getting Started"
fold = false
foldable = false
items = [
    { name = "Installation", href = "getting_started/installation" },
    { name = "Installation", href = "getting_started/installation" },
    { name = "Installation", href = "getting_started/installation" }
]

[[sections]]
name = "Basics"
link = "getting_started/installation"
items = [
    { name = "Installation", link = "getting_started/installation" },
    { name = "Installation", link = "getting_started/installation" },
    { name = "Installation", link = "getting_started/installation" }
]

# 从上一个版本直接复制
[[cloned]]
items = [

]

#
[[changed]]

[[removed]]