[package]
name = "doki-git"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/doki-land/doki"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
git2 = "0.13"
chrono = "*"
project-root ="*"

[dev-dependencies]

[features]
default = []