[package]
name = "doki-core"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/doki-land/doki"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
json5 = "0.4.1"
serde = {version = "1.0.132", features = ["derive"]}

[dependencies.sycamore]
version = "0.7.1"
features = ["experimental-builder-html"]

[dev-dependencies]

[features]
default = []
