[package]
name = "doki-core"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/doki-land/doki"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
git = {version = "0.1.0", package = "doki-git", optional = true}

serde = { version = "1.0.132", features = ["derive"] }
json5 = "0.4.1"

[dependencies.sycamore]
version = "0.7.1"
features = ["experimental-builder-html"]

[dev-dependencies]

[features]
default = []
compile_time_only = ["git"]