[package]
name = "doki-core"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/doki-land/doki"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
git = {version = "0.1.0", package = "doki-git", optional = true}
config = { version = "0.11", git = "https://github.com/mehcode/config-rs.git" }
#serde = { version = "1.0.132", features = ["derive"] }
notedown_ast = "0.16.1"
doki-error = "1.0.1"

[dependencies.sycamore]
version = "0.7.1"
features = ["experimental-builder-html"]
optional = true

[dependencies.dioxus]
version = "0.1.7"
optional = true

[dev-dependencies]

[features]
default = ["dioxus"]
compile_time_only = ["git"]